#!/usr/bin/env node
/**
 * build-html.js — 将 broadcast/ 源文件合并为 worker/broadcast-html.js
 *
 * 流程：
 *   1. 读 broadcast/src/*.js 按文件名排序拼接（替代单一 app.js）
 *   2. 读 broadcast/index.html + broadcast/styles.css
 *   3. 内联 CSS/JS → 转义模板字面量 → 输出
 * 配套：deploy.sh 在 wrangler deploy 前自动调用此脚本
 */
import { readFileSync, writeFileSync, readdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const BROADCAST_DIR = join(ROOT, "broadcast");
const SRC_DIR = join(BROADCAST_DIR, "src");
const OUTPUT = join(ROOT, "worker", "broadcast-html.js");

// ── 读取源文件 ────────────────────────────────────────────────────────────────
const html = readFileSync(join(BROADCAST_DIR, "index.html"), "utf-8");
const css = readFileSync(join(BROADCAST_DIR, "styles.css"), "utf-8");

// 读取 broadcast/src/*.js 按文件名排序拼接
const srcFiles = readdirSync(SRC_DIR)
  .filter((f) => f.endsWith(".js"))
  .sort();
const jsModules = srcFiles.map((f) => {
  const content = readFileSync(join(SRC_DIR, f), "utf-8");
  return `// ── ${f} ───────────────────────────────────────────────────────────────\n${content}`;
});
const js = jsModules.join("\n\n");

console.log(`📂 读取 ${srcFiles.length} 个模块: ${srcFiles.join(", ")}`);

// ── 内联替换 ──────────────────────────────────────────────────────────────────
// CSS: <link rel="stylesheet" href="./styles.css" /> → <style>…</style>
let result = html.replace(
  /<link\s+rel="stylesheet"\s+href="\.\/styles\.css"\s*\/?>/,
  `<style>\n${css}\n</style>`
);

// JS: <script src="./app.js" defer></script> → <script>…</script>
result = result.replace(
  /<script\s+src="\.\/app\.js"\s*defer\s*><\/script>/,
  `<script defer>\n${js}\n</script>`
);

// ── 转义模板字面量特殊字符（顺序敏感）────────────────────────────────────────
// 1. 反斜杠必须最先处理
// 2. 反引号 → \`
// 3. ${ → \${（防止 JS 模板引擎解析）
result = result.replace(/\\/g, "\\\\");
result = result.replace(/`/g, "\\`");
result = result.replace(/\$\{/g, "\\${");

// ── 组装最终输出 ──────────────────────────────────────────────────────────────
const output = `// AUTO-GENERATED by scripts/build-html.js — do not edit manually
// Source: broadcast/src/*.js + broadcast/{index.html, styles.css}
// Modules: ${srcFiles.join(", ")}
// Rebuild: node scripts/build-html.js
export const broadcastHtml = \`${result}\`;
`;

writeFileSync(OUTPUT, output, "utf-8");
console.log(`✅ build-html.js: ${OUTPUT} (${(output.length / 1024).toFixed(1)} KB)`);
