#!/usr/bin/env node
/**
 * build-html.js — 将 broadcast/ 源文件合并为 worker/broadcast-html.js
 *
 * 流程：读 index.html + styles.css + app.js → 内联替换 → 转义 → 输出模板字面量
 * 配套：deploy.sh 在 wrangler deploy 前自动调用此脚本
 */
import { readFileSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const BROADCAST_DIR = join(ROOT, "broadcast");
const OUTPUT = join(ROOT, "worker", "broadcast-html.js");

// 读取源文件
const html = readFileSync(join(BROADCAST_DIR, "index.html"), "utf-8");
const css = readFileSync(join(BROADCAST_DIR, "styles.css"), "utf-8");
const js = readFileSync(join(BROADCAST_DIR, "app.js"), "utf-8");

// 内联 CSS：替换 <link rel="stylesheet" href="./styles.css" /> 为 <style>...</style>
let result = html.replace(
  /<link\s+rel="stylesheet"\s+href="\.\/styles\.css"\s*\/?>/,
  `<style>\n${css}\n</style>`
);

// 内联 JS：<script src="./app.js" defer></script> → <script>...</script>
// 保留 defer 属性
result = result.replace(
  /<script\s+src="\.\/app\.js"\s*defer\s*><\/script>/,
  `<script defer>\n${js}\n</script>`
);

// 转义模板字面量特殊字符（顺序敏感）
// 1. 反斜杠必须最先处理，避免后续转义产生多余 `\`
// 2. 反引号 → \`
// 3. ${ → \${（防止 JS 模板引擎解析）
result = result.replace(/\\/g, "\\\\");
result = result.replace(/`/g, "\\`");
result = result.replace(/\$\{/g, "\\${");

// 组装最终输出
const output = `// AUTO-GENERATED by scripts/build-html.js — do not edit manually
// Source: broadcast/{index.html, styles.css, app.js}
// Rebuild: node scripts/build-html.js
export const broadcastHtml = \`${result}\`;
`;

writeFileSync(OUTPUT, output, "utf-8");
console.log(`✅ build-html.js: ${OUTPUT} (${(output.length / 1024).toFixed(1)} KB)`);
